# Generated by Django 2.0.6 on 2018-12-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slika',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
